### ISSUE TITLE
Include response body in JsonHttpException

### ISSUE THREAD

**Issue by nbouscal** [mrkkrp/req#72]
Currently `JsonHttpException` only contains the parse error, making it somewhat difficult to get at the response that failed to parse. In my experience I almost always want to see that response when I get a parse error, because usually my parser is wrong and the response will help me fix the parser. Are you open to adding the response body as another field to `JsonHttpException`? 

I can see an argument for making it configurable, e.g. to avoid leaking full response bodies into logs, but it's not immediately obvious to me how to do that cleanly.

**Comment by mrkkrp** [comment]
Yes I think it's a good idea.

**Comment by mrkkrp** [comment]
I considered adding this in version 3.0.0, but the conditional inclusion of body seems to require passing configuration parameters to `getHttpResponse` which is otherwise not necessary.

In fact it's already possible to achieve what you want with the `reqBr` function to get full control over consumption of the response. You can mostly re-use implementation of `getHttpResponse` for `JsonResponse` here.
