### ISSUE TITLE
Add `Default HttpConfig` instance

### ISSUE THREAD

**Issue by tysonzero** [mrkkrp/req#88]
Just upgraded `req` and it broke my codebase in a bunch of places because of `def` no longer typechecking.

I understand _also_ exporting `defaultHttpConfig` for people who don't want to specify `data-default-class` in their cabal file.

However I don't see a reason for not continuing to support `def` for those (like myself) who prefer it. It's an incredibly light dependency.

**Comment by mrkkrp** [comment]
> Just upgraded `req` and it broke my codebase in a bunch of places because of `def` no longer typechecking.

That's why there was a major version bump. When you're upgrading to a new major version, it is normal for things to break.

> I understand also exporting `defaultHttpConfig` for people who don't want to specify `data-default-class` in their cabal file.

It is not at all about the questionable burden of adding dependencies to Cabal files. If it were, who could complain about such a minor nuisance?

> However I don't see a reason for not continuing to support `def` for those (like myself) who prefer it. It's an incredibly light dependency.

Using `data-default` or `data-default-class` in Haskell is always a mistake. Why?

* *It adds no value.* For simple types like `Int` or `Bool` there is no universal default value because the concepts they represent are too general. For for more complex and specific types nothing beats a non-polymorphic value, which also can build on other non-polymorphic values.

* *It makes incorrect code typecheck.* When you have your defaults as non-polymorphic values, you cannot use the values where compiler expects an incompatible type. IOW, every time you use a non-polymorphic default you are explicit about the type you mean. With `def`, as long as you happen to put it in a place where GHC expects something that has a `Default` instance it will happily accept it.

* *There may be more than one default value per type.*

* *It is an extra dependency.* However light, no dependency is better than one.

I understand you, because I myself once fell into the pernicious trap of `data-default`. Later, however, I rectified my mistake. I propose you refactor your code to eliminate `data-default`, too.

**Comment by tysonzero** [comment]
> That's why there was a major version bump. When you're upgrading to a new major version, it is normal for things to break.

cheapskate
wai-extra
xml-conduit
pandoc

**Comment by tysonzero** [comment]
> That's why there was a major version bump. When you're upgrading to a new major version, it is normal for things to break.

I know it can happen sometimes, but it's still preferable to avoid it when possible, so I figured I would mention it.

> It is not at all about the questionable burden of adding dependencies to Cabal files. If it were, who could complain about such a minor nuisance?

I was just paraphrasing the PR that got rid of this instance:

"The motivation behind this PR is to avoid getting bitten in the a** about a missing dependency every time one tries to make an HTTP call in a new project."

> It adds no value. For simple types like `Int` or `Bool` there is no universal default value because the concepts they represent are too general.

I largely agree with that. Those types probably should not have been given instances.

> For for more complex and specific types nothing beats a non-polymorphic value, which also can build on other non-polymorphic values.

I completely disagree with this. I'd much rather just type `def`. Instead I have to open up hackage and CTRL-F "defaultFoo" hoping that it will match or scrolling around a bunch if it doesn't. Then I have to go ahead and add that to the import list of every file that uses it, instead of just throwing `def` in my project-specific prelude and not worrying about it.

> It makes incorrect code typecheck.

If this is something you are worried about you can always use TypeApplications and do `def @HttpConfig`. That way I still get to avoid looking through Hackage or adding extra unnecessary imports.

I also have used `def` a ton and have not once run into this problem. I particularly think that if some of the questionable instances were removed then this would become basically impossible.

> There may be more than one default value per type.

Agreed. In such a case the class shouldn't be used. Just like how we don't have `Monoid Int` and I am perfectly happy with the lack of that instance. However in cases where users are realistically just going to be CTRL-F-ing "defaultFoo" through hackage, typeclasses can save them that time.

> It is an extra dependency. However light, no dependency is better than one.

Any non-trivial project will inevitably depend on it. I use at least four libraries that *directly* provide me instances, not to mention how many others indirectly depend on libraries that use it.

> I propose you refactor your code to eliminate data-default, too.

It's an extremely convenient and useful class, and it allows for nice helper functions like `orDef :: Default a => Maybe a -> a`. I honestly wish it was a superclass of `Monoid` for exactly that reason. This would also allow for niceness like an `AffineFoldable` subclass of `Foldable` that provides `affineFold :: Default a => f a -> a` instead of the less general `fold :: Monoid a => f a -> a`.

It's not even technically possible for me to avoid it without major breaking changes to several large libraries that I depend on, as they all either directly export `def :: Default a => a`, or they export nothing and expect you to use `def` directly.
